---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
1. Load the Data
```
activity <- read.csv(file = "C:/Users/rli/Documents/activity.csv")
```
2 Process the data into a format suitable for the analysis
```
library(reshape2)
actMeltDate <- melt(activity, id.vars="date", measure.vars="steps", na.rm=FALSE)
actCastDate <- dcast(actMeltDate, date ~ variable, sum)
```


## What is mean total number of steps taken per day?
1. Calculate the total number of steps taken per day
```
total.steps <- tapply(activity$steps, activity$date, FUN=sum, na.rm=TRUE)
```
2. Make a histogram of the total number of steps taken each day
```
plot(actCastDate$date, actCastDate$steps, type="h", main="Histogram of Daily Steps", xlab="Date", ylab="Steps per Day", col="blue", lwd=8)
abline(h=mean(actCastDate$steps, na.rm=TRUE), col="red", lwd=2)
```
Please refer to 1.PNG

3. Calculate and report the mean and median of the total number of steps taken per day
```
mean(total.steps, na.rm=TRUE)
median(total.steps, na.rm=TRUE)
```
## [1] "Mean Steps per Day = 10766.1886792453"
## [1] "Median Steps per Day = 10765"


## What is the average daily activity pattern?
1. Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
```
library(ggplot2)
averages <- aggregate(x=list(steps=activity$steps),by=list(interval=activity$interval),FUN=mean, na.rm=TRUE)
ggplot(data=averages,aes(x=interval, y=steps)) + 
geom_line()+
xlab("5-minute interval") +
ylab("average number of steps taken")
```
Please refer to 2.PNG

2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps
```
averages[which.max(averages$steps),]
```
## [1] "Interval with max value = 835"


## Imputing missing values
Calculate and report the total number of missing values in the dataset
```
missing <-is.na(activity$steps)
table(missing)
```
Devise a strategy for filling in all of the missing values in the dataset and Create a new dataset that is equal to the original dataset but with the missing data filled in

Strategy description:  Since there are a considerable number of missing/NA values (2,304), I will replace NAs with the mean for the particular interval number. For example: if the average number of steps taken during interval x is y, I will replace each NA with the corresponding y value for that row. I will then recalculate the steps per day to see how much it differs from the original result (with NAs included).
```
stepsPerInt <- actCastInt
actNoNA <- activity
actMerge = merge(actNoNA, stepsPerInt, by="interval", suffixes=c(".act", ".spi"))
naIndex = which(is.na(actNoNA$steps))
actNoNA[naIndex,"steps"] = actMerge[naIndex,"steps.spi"]
```
Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day
```
actMeltDateNoNA <- melt(actNoNA, id.vars="date", measure.vars="steps", na.rm=FALSE)
actCastDateNoNA <- dcast(actMeltDateNoNA, date ~ variable, sum)
plot(actCastDateNoNA$date, actCastDateNoNA$steps, type="h", main="Histogram of Daily Steps (Imputted NA Values)", xlab="Date", ylab="Steps", col="gray", lwd=8)
abline(h=mean(actCastDateNoNA$steps), col="red", lwd=2)
```
Please refer to 3.PNG

## Are there differences in activity patterns between weekdays and weekends?
Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day
```
weekday.or.weekend <- function(date) {
 day <- weekdays(date)
 if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
 return("weekday")
 else if (day %in% c("Saturday", "Sunday"))
 return("weekend")
 else
 stop("invalid date")
}
filled.activity$date <-as.Date(filled.activity$date)
filled.activity$day <-sapply(filled.activity$date,FUN=weekday.or.weekend)
```
Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis)
```
averages <- aggregate(steps ~ interval + day, data=filled.activity, mean)
library(ggplot2)
ggplot(averages, aes(interval, steps)) + geom_line() + facet_grid(day ~ .) +
xlab("5-minute interval") + ylab("Number of steps")
```
Please refer to 4.PNG

